/** Comprehensive ESE/IES Civil formula & concept revise notes. */

export type IesReviseBlock = {
  subject: string;
  title: string;
  paper: "ce_paper1" | "ce_paper2" | "both";
  points: string[];
};

export const IES_REVISE_NOTES: IesReviseBlock[] = [
  {
    subject: "engineering_mechanics",
    title: "Engineering Mechanics",
    paper: "ce_paper1",
    points: [
      "ΣFₓ = 0, ΣFᵧ = 0, ΣM = 0 for static equilibrium.",
      "Moment = Force × perpendicular distance; couple = equal opposite forces.",
      "Centroid of triangle: h/3 from base; semicircle: 4R/(3π) from diameter.",
      "Parallel axis: I = I_g + A d². Perpendicular axis (planar): I_z = I_x + I_y.",
      "Friction: F ≤ μN; impending F = μN. Angle of friction φ = tan⁻¹ μ.",
      "Work–energy: U = ΔKE. Impulse–momentum: ∫F dt = Δ(mv).",
      "Virtual work: δU = 0 at equilibrium for ideal systems.",
    ],
  },
  {
    subject: "solid_mechanics",
    title: "Solid Mechanics / Strength of Materials",
    paper: "ce_paper1",
    points: [
      "σ = P/A; ε = δ/L; E = σ/ε (elastic). G = τ/γ. Poisson ν = −ε_lat/ε_long.",
      "Bulk K = −p/(ΔV/V); relation E = 2G(1+ν) = 3K(1−2ν).",
      "Thermal: δ_free = α L ΔT; if constrained σ = E α ΔT (full fixity).",
      "Bending: σ = M y / I; τ = V Q / (I b). Neutral axis at centroid.",
      "Section modulus Z = I/y_max; elastic section modulus for rectangle bd²/6.",
      "Torsion (circular): τ/r = T/J = Gθ/L; J = π d⁴/32 (solid).",
      "Euler: P_e = π² E I / L_e². Both ends hinged L_e = L; fixed L_e = L/2; fixed–free 2L; fixed–hinged 0.7L.",
      "Rankine: 1/P_r = 1/P_e + 1/σ_c A. Slenderness λ = L_e / k; k = √(I/A).",
      "Mohr’s circle: centre (σₓ+σᵧ)/2; radius √(((σₓ−σᵧ)/2)² + τ²).",
      "Principal stresses: σ_{1,2} = (σₓ+σᵧ)/2 ± R. Max shear = R (plane stress).",
      "Strain energy axial: U = P²L/(2AE). Bending: ∫ M² dx /(2EI).",
      "Leaf spring / helical spring formulas — check closed-coil τ = 16WR/(πd³)×K_w.",
    ],
  },
  {
    subject: "structural_analysis",
    title: "Structural Analysis",
    paper: "ce_paper1",
    points: [
      "Plane truss static indeterminacy: m + r − 2j. Space truss: m + r − 3j.",
      "Plane rigid frame: D_s = (3m + r) − 3j. Beams continuous: similar 3m+r−3j with joints.",
      "Degree of kinematic indeterminacy (sway neglected care): often 3j − r′ − m′ constraints.",
      "IL for simple beam reaction at A: 1 at A → 0 at B. BM at midspan peak  L/4 under unit load.",
      "Moment distribution: stiffness K = 4EI/L (far fixed), 3EI/L (far hinged). DF = K_i/ΣK.",
      "Carry-over factor = +1/2 (prism, far fixed). Clapeyron three-moment equation for continuous beams.",
      "Slope-deflection: M_ab = M_fixed + (2EI/L)(2θ_a + θ_b − 3ψ).",
      "Castigliano: δ = ∂U/∂P. Maxwell–Betti reciprocal theorem.",
      "Arch (two-hinged): H from ∫(M_y y)/EI = 0 (temperature/rib shortening separate).",
      "Influence lines for truss: Müller–Breslau — release constraint, deflect shape is IL.",
    ],
  },
  {
    subject: "design_concrete",
    title: "RCC & Prestressed Concrete (IS 456 / IS 1343)",
    paper: "ce_paper1",
    points: [
      "LSM concrete ε_cu = 0.0035 (flexure); pure compression 0.002. γ_m concrete 1.5; steel 1.15.",
      "Xu,max/d = 0.53 (Fe250), 0.48 (Fe415), 0.46 (Fe500) for singly reinforced limiting.",
      "Mu,lim = 0.36 fck b xu (d − 0.42 xu). Lever arm z ≈ d − 0.42 xu.",
      "Pt,lim ≈ 0.96 fck/fy × (xu/d) (order of magnitude — use code tables in exam).",
      "Shear: τ_c from Table 19 IS 456; τ_c,max Table 20. Stirrups Vus = 0.87 fy Asv d / sv.",
      "Development length Ld = φ σ_s / (4 τ_bd). Bond stress τ_bd depends on grade & bar type.",
      "Min Ast slab = 0.12% HYSD / 0.15% mild. Min shear rein. when τ_v > 0.5 τ_c.",
      "Effective flange width T-beam: min of code expressions (bw + l0/6 + …).",
      "Columns: Pu = 0.4 fck Ac + 0.67 fy Asc (axial short). Min Asc 0.8%, max 4%.",
      "Footing: soil pressure q = P/A ± M/Z. One-way & punching shear checks critical.",
      "Prestress: loss = elastic + creep + shrinkage + relaxation + anchorage + friction (μ, k).",
      "PSC: stress at transfer / service; kern points for no-tension (rectangular kern d/6).",
    ],
  },
  {
    subject: "design_steel",
    title: "Steel Design (IS 800:2007)",
    paper: "ce_paper1",
    points: [
      "Partial factors: γ_m0 = 1.10, γ_m1 = 1.25 (resistance). Load factors per IS 800 Table 4.",
      "Tension member: Tdg = Ag fy/γ_m0; Tdn = 0.9 Anc fu/γ_m1; block shear separate.",
      "Net area: deduct holes; stagger: +s²/4g per chain. Shear lag β for angles.",
      "Compression: design strength χ Ag fy / γ_m0; χ from buckling class a–d curves.",
      "Slenderness λ = KL/r; effective length factors per end restraint (Table 11).",
      "Beam: Md = β_b Z_p fy / γ_m0 ≤ 1.2 Ze fy/γ_m0 (for plastic). Check LATB if unsupported.",
      "Shear capacity Vd = Av fy /(√3 γ_m0). Web buckling / bearing at supports.",
      "Fillet weld: strength = f_u/√3 / γ_mw × throat × length; throat = 0.7 t_min (usual).",
      "Bolt: shear Vdsb = fu/√3 (nn Anb + ns Asb)/γ_mb; bearing Vdpb = 2.5 kb d t fu / γ_mb.",
      "Plate girder: stiffeners when d/t_w limits exceeded; flange/web local buckling checks.",
    ],
  },
  {
    subject: "building_materials",
    title: "Building Materials & Construction",
    paper: "ce_paper1",
    points: [
      "OPC: initial set ≥ 30 min; final ≤ 600 min. Consistency Vicat ~25–30% water.",
      "Fineness: Blaine / sieve. Soundness: Le Chatelier ≤ 10 mm (OPC).",
      "Compound: C3S early strength; C2S later; C3A heat/flash; C4AF flux.",
      "Concrete grades M15–M80; target mean fck + 1.65 s. W/C controls strength & durability.",
      "Workability: slump, compaction factor, Vee-Bee. Admixtures: plasticizer, air-entrain, retard.",
      "Brick: class designation by compressive strength; water absorption limits; frog placement.",
      "Timber: seasoning, defects, season moisture ~12% furniture. Plywood grades.",
      "Steel: Fe250/415/500/550; HYSD / TMT. Elongation & bend tests.",
      "Aggregates: fineness modulus, crushing/impact/abrasion values; flakiness/elongation.",
      "Mortar grades; plaster ratios; damp-proofing & expansion joints concepts.",
    ],
  },
  {
    subject: "construction_mgmt",
    title: "Construction Management, Estimating & Equipment",
    paper: "ce_paper1",
    points: [
      "CPM: EST/EFT forward; LST/LFT backward. Total float = LST−EST = LFT−EFT.",
      "Free float = EST_succ − EFT. Independent float = EST_succ − LFT_pred − duration.",
      "PERT: te = (to+4tm+tp)/6; σ² = ((tp−to)/6)²; project σ = √Σσ² on critical path.",
      "Crashing: cost slope = (Cc−Cn)/(Tn−Tc); crash cheapest critical activity first.",
      "EOQ = √(2DS/H). ABC inventory. Resource levelling vs smoothing.",
      "Estimating: plinth area, floor area, carpet; contingencies ~3–5%; work-charged.",
      "Rate analysis: labour + material + tools + overhead + profit. Lead & lift.",
      "Earthwork: mid-section / trapezoidal / Simpson. Mass haul diagram.",
      "Equipment: output = (capacity × cycles/h × efficiency × fill factor).",
      "Contracts: item rate, lump sum, cost-plus, turnkey; earnest money, security deposit.",
    ],
  },
  {
    subject: "fluid_mechanics",
    title: "Fluid Mechanics & Hydraulic Machines",
    paper: "ce_paper2",
    points: [
      "ρ water ≈ 1000 kg/m³; γ = ρg ≈ 9.81 kN/m³. Absolute vs gauge pressure.",
      "Hydrostatics: p = ρ g h. Manometer Δp = ρgΔh. Force on plane surface F = p_c A; y_p = I_G sin²θ /(A y_c) + y_c.",
      "Buoyancy F_B = γ V_displaced. Stability: metacentric height GM = BM − BG; BM = I/V.",
      "Continuity: ρAV = const; incompressible A₁V₁ = A₂V₂.",
      "Bernoulli: p/ρg + V²/2g + z = const (+ losses). Pitot: V = √(2g h).",
      "Momentum: ΣF = ρQ(V_out − V_in). Force on vane / pipe bend.",
      "Laminar pipe: Hagen–Poiseuille Q = π Δp R⁴ /(8 μ L); u_max = 2 V_avg; f = 64/Re.",
      "Darcy–Weisbach: h_f = f L V² /(2 g D). Moody / Colebrook for f turbulent.",
      "Minor losses: K V²/2g (entrance, exit, bend, valve). Equivalent length method.",
      "Orifice: Q = Cd a √(2gH). Time to empty tank ∫ A dH /(Cd a √(2gH)).",
      "Weirs: rectangular Q = (2/3) Cd L √(2g) H^{3/2}; triangular (8/15)…",
      "Dim analysis: Reynolds, Froude, Weber, Mach. Models: Fr similarity open channel.",
      "Turbines: Pelton impulse; Francis/Kaplan reaction. P = ρ g Q H η. Specific speed Ns.",
      "Pumps: centrifugal H–Q curve; NPSH; affinity laws Q∝N, H∝N², P∝N³.",
    ],
  },
  {
    subject: "hydrology",
    title: "Hydrology",
    paper: "ce_paper2",
    points: [
      "Hydrologic cycle. Precipitation measurement: Thiessen, isohyetal, arithmetic mean.",
      "Φ-index / W-index infiltration. Horton infiltration equation.",
      "Runoff: rational Q = C i A (consistency of units!). Curve number SCS.",
      "Unit hydrograph: 1 cm excess over catchment in duration D; linearity & time-invariance.",
      "S-curve / instantaneous UH methods to change duration. Hydrograph separation.",
      "Flood routing: Muskingum X, K; storage indication reservoir routing.",
      "Gumbel extreme value; recurrence interval T = (n+1)/m. Risk = 1−(1−1/T)^n.",
      "Groundwater: Darcy q = k i A; Dupuit–Thiem steady well formulas.",
      "Specific yield / retention; storativity confined aquifers.",
      "Flood frequency & design flood concepts for spillways.",
    ],
  },
  {
    subject: "irrigation",
    title: "Irrigation Engineering",
    paper: "ce_paper2",
    points: [
      "Duty D (ha/cumec), Delta Δ (m), Base period B (days): Δ = 8.64 B / D (approx SI).",
      "Kor depth / kor period. Consumptive use; crop water requirement = ET / efficiency.",
      "Canal types: lined/unlined; Kennedy / Lacey silt theories; regime equations.",
      "Lacey: P = 4.75 √Q; V = (Q f² / 140)^{1/6}; R = 5V²/(2f) etc. (memorise set).",
      "Cross drainage: aqueduct, syphon aqueduct, super passage, level crossing.",
      "Diversion headworks: weir vs barrage; stilling basin; fish ladder; under-sluices.",
      "Gravity dam: σ = ΣV/A ± ΣM y / I; middle-third / no-tension; uplift, silt, ice loads.",
      "Spillways: ogee, chute, siphon; energy dissipation — hydraulic jump Froude.",
      "Waterlogging: causes, effects, drainage; lining seepage control.",
      "Irrigation efficiencies: conveyance, application, storage, distribution.",
    ],
  },
  {
    subject: "environmental",
    title: "Environmental Engineering",
    paper: "ce_paper2",
    points: [
      "Population forecast: arithmetic, geometric, incremental increase, logistic.",
      "Design periods: water supply components typically 15–30 years (remember typical values).",
      "Per capita demand India (CPHEEO) ~135–200+ lpcd depending on city class / exam year.",
      "Coagulation: alum / iron salts; jar test. Flocculation → sedimentation → filtration → disinfection.",
      "Settling: Stokes v_s = (ρ_s−ρ) g d² /(18 μ). Overflow rate = Q/A.",
      "Filter: rapid sand rates ~3000–6000 L/m²/h order; slow sand much lower.",
      "Chlorine: demand = dose − residual; breakpoint chlorination.",
      "Hardness: Ca²⁺+Mg²⁺ as CaCO₃; carbonate vs non-carbonate; lime–soda softening reactions.",
      "BOD₅ = L₀(1−e^{−kt}); COD ≥ BOD; TOD. Oxygen sag: Streeter–Phelps.",
      "Sewer design: Manning / Hazen; self-cleansing velocity ~0.6–0.9 m/s typical.",
      "ASP: F/M, SRT (θ_c), MLSS, recycle ratio. Trickling filter NRC / Rankin formulas.",
      "Sludge: volume ∝ 1/solids%; digestion gas ~ methane. Septic tank detention.",
      "Air pollution: primary/secondary; SPM, SO₂, NOx, CO; plume types (neutral/looping/…).",
      "Noise: L_eq, L_dn; dB addition rules (equal sources +3 dB).",
    ],
  },
  {
    subject: "geotech",
    title: "Geotechnical Engineering",
    paper: "ce_paper2",
    points: [
      "Phase relations: e = Vv/Vs; n = e/(1+e); S = Vw/Vv; w = Ww/Ws; G = γ_s/γ_w.",
      "S e = w G. γ_d = G γ_w /(1+e); γ_sat = (G+e)γ_w/(1+e); γ = (G+S e)γ_w/(1+e).",
      "Atterberg: LL, PL, SL; PI = LL−PL; LI, activity. IS classification GW–CH etc.",
      "Compaction: OMC & MDD Proctor; modified Proctor higher energy → higher MDD, lower OMC.",
      "Permeability: lab constant/falling head; field pumping. Stratified k_h, k_v averages.",
      "Seepage: Laplace; flow net q = k H N_f/N_d. Exit gradient; piping. Quick sand i_cr = (G−1)/(1+e).",
      "Effective stress σ′ = σ − u (Terzaghi). Capillary rise h_c = (2σ cosθ)/(ρ g r).",
      "Consolidation: Mv, Cv; Tv = Cv t / H_dr²; U≈√(π Tv/4) for U<60%. Secondary compression.",
      "Shear: Mohr–Coulomb τ = c + σ tanφ. UU, CU, CD. Direct shear / triaxial / vane.",
      "Earth pressure: Rankine σ_a = K_a σ_v − 2c√K_a; K_a = (1−sinφ)/(1+sinφ); K_p inverse.",
      "Coulomb wedge theory; Culmann. Braced cuts apparent pressure diagrams.",
      "Bearing: Terzaghi q_ult = c Nc sc + γ Df Nq sq + 0.5 γ B Nγ sγ. Net / safe / allowable.",
      "Settlement: immediate + consolidation + secondary. Plate load test interpretation.",
      "Pile: static formulas, dynamic Engineering News; group efficiency; negative skin friction.",
      "Slope stability: Swedish slip circle; Bishop; infinite slope i_c = tanφ (c=0 dry).",
    ],
  },
  {
    subject: "surveying",
    title: "Surveying & Geology",
    paper: "ce_paper2",
    points: [
      "Chain survey: ranging, offsets. Compass: FB/BB; local attraction; declination.",
      "Levelling: HI = RL + BS; RL = HI − FS. Rise/fall method checks.",
      "Curvature 0.0785 D² (D km) m; refraction ≈ 1/7 curvature; combined 0.0673 D².",
      "Contour: horizontal equivalent = CI / tan(slope). Interpolation.",
      "Theodolite: face left/right; transit. Horizontal angle reiteration / repetition.",
      "Tacheometry: D = k s + c (stadia). Analytic lens → c≈0.",
      "Traverse: Bowditch (compass), transit rule (theodolite). Closing error distribution.",
      "Triangulation / trilateration. GPS: code vs carrier; DGPS; GIS layers.",
      "Photogrammetry: scale = f/H; relief displacement. Remote sensing resolutions.",
      "Geology: rocks igneous/sedimentary/metamorphic; folds faults joints; aquifers; tunnel geology.",
    ],
  },
  {
    subject: "transportation",
    title: "Transportation Engineering",
    paper: "ce_paper2",
    points: [
      "SSD = v t + v²/(2 g f) (± grade: 2g(f±n)). ISD ≈ 2 SSD (plain, two-way).",
      "Overtaking sight distance formula with reaction & overtaking time (IRC).",
      "Superelevation e + f = V²/(g R); design e limited (IRC max ~7%); radius from design speed.",
      "Transition spiral: Ls ≈ V³/(C R) empirical IRC. Extra widening We = n(l²/2R)+V/(9.5√R).",
      "Gradient: ruling, limiting, exceptional; grade compensation on curves.",
      "Pavement: flexible vs rigid. CBR design (IRC:37). Wheel load stress Westergaard (IRC:58).",
      "Traffic: spot / space mean speed; flow q = k v; Poisson arrivals; PCU factors.",
      "Signals: Webster cycle C0 = (1.5L+5)/(1−Y); green splits by y_i.",
      "Highway capacity & LOS concepts. Rotary design weaving.",
      "Railway: gauge, cant e = GV²/(127 R); sleeper density; creep; points & crossings.",
      "Airport: runway orientation wind rose; basic runway length corrections (elevation, temp, gradient).",
      "Bitumen: penetration, softening point, ductility, viscosity grading; Marshall mix.",
    ],
  },
];
